
name: ClassClock
githubURL: https://github.com/MoralCode/ClassClock
discordURL: https://discord.classclock.app
slackURL: https://join.slack.com/t/classclock/shared_invite/zt-6k65iqmt-oNO5YOWEQ7dOOCu0vbkEZw
blueskyURL: https://bsky.app/profile/did:plc:7nnfhmgll4buy4za6uyhlpjg
twitterURL: https://twitter.com/classclockapp
instagramURL: https://www.instagram.com/classclockapp/
gitterURL: https://gitter.im/MoralCode/ClassClock
matrixURL: https://matrix.to/#/#classclockapp:matrix.org
mailinglistURL: https://groups.google.com/g/classclock/

plugins:
  - jekyll-sitemap