
name: ClassClock
githubURL: https://github.com/MoralCode/ClassClock
discordURL: https://discord.classclock.app
slackURL: https://join.slack.com/t/classclock/shared_invite/zt-6k65iqmt-oNO5YOWEQ7dOOCu0vbkEZw
twitterURL: https://twitter.com/classclockapp
instagramURL: https://www.instagram.com/classclockapp/
gitterURL: https://gitter.im/MoralCode/ClassClock


plugins:
  - jekyll-sitemap